---
# Panorama connection details
panorama_host: "panorama.example.com"
panorama_user: "admin"
panorama_pass: "{{ vault_panorama_pass }}"

# Device group and template
device_group_name: "production"
template_name: "vm-series-template"

# Interface configurations
interfaces:
  - name: "ethernet1/1"
    mode: "layer3"
    ip: "10.0.1.1/24"
    management_profile: "allow-all"
  - name: "ethernet1/2"
    mode: "layer3"
    ip: "10.0.2.1/24"
    management_profile: "allow-all"

# Security zone configurations
security_zones:
  - name: "trust"
    zone_profile: "DefaultZoneProfile"
    log_setting: "DefaultLogSetting"
    enable_userid: true
  - name: "untrust"
    zone_profile: "DefaultZoneProfile"
    log_setting: "DefaultLogSetting"
    enable_userid: false

# Security rule configurations
security_rules:
  - name: "allow-internal"
    source_zones: ["trust"]
    destination_zones: ["untrust"]
    source_addresses: ["10.0.0.0/8"]
    destination_addresses: ["any"]
    applications: ["any"]
    action: "allow"
  - name: "deny-all"
    source_zones: ["any"]
    destination_zones: ["any"]
    source_addresses: ["any"]
    destination_addresses: ["any"]
    applications: ["any"]
    action: "deny"

# NAT rule configurations
nat_rules:
  - name: "source-nat"
    source_zones: ["trust"]
    destination_zones: ["untrust"]
    source_addresses: ["10.0.0.0/8"]
    destination_addresses: ["any"]
    service: "any"
    nat_type: "ipv4"
