frontend:
  - src/frontend/**/*
  - "**/*.tsx"
  - "**/*.css"
  - "**/*.scss"
  - "**/*.jsx"

backend:
  - src/backend/**/*
  - "**/*.ts"
  - "**/*.js"
  - "**/*.json"

documentation:
  - docs/**/*
  - "**/*.md"
  - "**/*.rst"
  - "**/*.txt"

security:
  - "**/security/**"
  - "**/auth/**"
  - "**/cve/**"
  - "**/config/**"

performance:
  - "**/performance/**"
  - "**/optimization/**"
  - "**/cache/**"

infrastructure:
  - docker/**/*
  - "**/Dockerfile*"
  - "**/docker-compose*"
  - "**/kubernetes/**"
  - "**/terraform/**"

testing:
  - "**/test/**"
  - "**/tests/**"
  - "**/*.test.*"
  - "**/*.spec.*"
  - "**/__tests__/**"

bug:
  - "**/fix/**"
  - "**/bug/**"
  - "**/issue/**"

enhancement:
  - "**/feature/**"
  - "**/enhancement/**"
  - "**/improvement/**"
