version: "3.8"

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_CVE_API_URL=http://localhost:3002
    depends_on:
      - backend

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://db:27017/security-config
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
      - NODE_ENV=development
    depends_on:
      - db
      - redis

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
