---
- name: Configure VM-Series Firewall
  hosts: vm_series
  gather_facts: false
  connection: local
  vars:
    panorama_hostname: "{{ panorama_host }}"
    panorama_username: "{{ panorama_user }}"
    panorama_password: "{{ panorama_pass }}"
    device_group: "{{ device_group_name }}"
    template: "{{ template_name }}"

  tasks:
    - name: Configure interfaces
      panos_interface:
        provider:
          hostname: "{{ panorama_hostname }}"
          username: "{{ panorama_username }}"
          password: "{{ panorama_password }}"
        name: "{{ item.name }}"
        mode: "{{ item.mode }}"
        ip: "{{ item.ip }}"
        enable_dhcp: "{{ item.enable_dhcp | default(false) }}"
        management_profile: "{{ item.management_profile | default('allow-all') }}"
        template: "{{ template }}"
        device_group: "{{ device_group }}"
      loop: "{{ interfaces }}"

    - name: Configure security zones
      panos_security_zone:
        provider:
          hostname: "{{ panorama_hostname }}"
          username: "{{ panorama_username }}"
          password: "{{ panorama_password }}"
        name: "{{ item.name }}"
        zone_profile: "{{ item.zone_profile | default('DefaultZoneProfile') }}"
        log_setting: "{{ item.log_setting | default('DefaultLogSetting') }}"
        enable_userid: "{{ item.enable_userid | default(false) }}"
        template: "{{ template }}"
        device_group: "{{ device_group }}"
      loop: "{{ security_zones }}"

    - name: Configure security rules
      panos_security_rule:
        provider:
          hostname: "{{ panorama_hostname }}"
          username: "{{ panorama_username }}"
          password: "{{ panorama_password }}"
        name: "{{ item.name }}"
        source_zones: "{{ item.source_zones }}"
        destination_zones: "{{ item.destination_zones }}"
        source_addresses: "{{ item.source_addresses }}"
        destination_addresses: "{{ item.destination_addresses }}"
        applications: "{{ item.applications }}"
        action: "{{ item.action }}"
        template: "{{ template }}"
        device_group: "{{ device_group }}"
      loop: "{{ security_rules }}"

    - name: Configure NAT rules
      panos_nat_rule:
        provider:
          hostname: "{{ panorama_hostname }}"
          username: "{{ panorama_username }}"
          password: "{{ panorama_password }}"
        name: "{{ item.name }}"
        source_zones: "{{ item.source_zones }}"
        destination_zones: "{{ item.destination_zones }}"
        source_addresses: "{{ item.source_addresses }}"
        destination_addresses: "{{ item.destination_addresses }}"
        service: "{{ item.service }}"
        nat_type: "{{ item.nat_type }}"
        template: "{{ template }}"
        device_group: "{{ device_group }}"
      loop: "{{ nat_rules }}"

    - name: Commit configuration
      panos_commit:
        provider:
          hostname: "{{ panorama_hostname }}"
          username: "{{ panorama_username }}"
          password: "{{ panorama_password }}"
        device_group: "{{ device_group }}"
