name: API Documentation

on:
  push:
    branches: [main]
    paths:
      - "src/backend/**/*.ts"
      - "src/backend/**/*.js"
      - ".github/workflows/api-docs.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/backend/**/*.ts"
      - "src/backend/**/*.js"
      - ".github/workflows/api-docs.yml"

jobs:
  generate-api-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: |
          cd src/backend
          npm ci
          npm install -g typedoc

      - name: Generate API Documentation
        run: |
          cd src/backend
          typedoc --out docs/api src/

      - name: Deploy API Documentation
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/backend/docs/api
          destination_dir: api-docs
          commit_message: ${{ github.event.head_commit.message }}
