name: Branch Protection

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Check if direct push to main
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "❌ Direct pushes to main branch are not allowed."
            echo "Please create a pull request instead."
            exit 1
          fi
