name: Branch Protection

on:
  push:
    branches: [main]

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Protect main branch
        uses: actions/github-script@v7
        with:
          script: |
            const branch = 'main';
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            try {
              await github.rest.repos.updateBranchProtection({
                owner,
                repo,
                branch,
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'lint',
                    'test',
                    'security'
                  ]
                },
                enforce_admins: true,
                required_pull_request_reviews: {
                  required_stale_reviews: 1,
                  require_code_owner_reviews: true,
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true
                },
                restrictions: null
              });

              console.log(`Branch protection rules updated for ${branch}`);
            } catch (error) {
              console.error('Error updating branch protection:', error);
            }
