name: Prevent Commits

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit messages
        run: |
          git log -1 --pretty=%B | grep -q "\[ALLOW_COMMIT\]" || {
            echo "❌ Commits are currently disabled."
            echo "To commit, add '[ALLOW_COMMIT]' to your commit message."
            echo "Example: git commit -m '[ALLOW_COMMIT] Your commit message'"
            exit 1
          }
